//! Differential oracle for NTT-family ops, backed by Plonky3.
//!
//! Speaks the harness vector wire format. Each stdin line is
//!
//!     x0 x1 ... x_{n-1} [: y0 y1 ... y_{n-1}]
//!
//! with unsigned canonical BabyBear residues. For every line the oracle
//! recomputes the expected outputs with Plonky3's DFT and writes
//! `x0 ... x_{n-1} : y0' ... y_{n-1}'` to stdout, so its output is itself a
//! valid vector stream for `verify_arith.py`. With `--check`, a line that
//! already carries expected outputs (e.g. a frozen vector file, or the Python
//! generator's stream) is additionally cross-checked: any disagreement between
//! the incoming reference outputs and Plonky3's is a hard failure. Blank lines
//! and `#` comments are skipped; anything else malformed is a hard error — an
//! oracle that silently drops vectors weakens the comparison.
//!
//! Usage:
//!     p3_oracle --op {ntt|intt} --n N [--check]
//!
//!     cat test_vectors/matrix_ntt/*.txt | p3_oracle --op ntt --n 8 --check
//!     generators/matrix.py --op matrix_ntt | p3_oracle --op ntt --n 8 --check

use std::io::{self, BufRead, Write};
use std::process::ExitCode;

use p3_baby_bear::BabyBear;
use p3_dft::{Radix2Dit, TwoAdicSubgroupDft};
use p3_field::{PrimeCharacteristicRing, PrimeField32, TwoAdicField};

const P: u32 = BabyBear::ORDER_U32;

/// TRZK's multiplicative generator for BabyBear; mirrors `gGen` in the Lean
/// specs and `g = 31` in `generators/matrix.py`.
const TRZK_GENERATOR: u32 = 31;

#[derive(Clone, Copy, PartialEq)]
enum Op {
    Ntt,
    Intt,
}

/// Convention reconciliation (the conversion site).
///
/// TRZK (`TRZK/MatrixLower.lean`, `generators/matrix.py`):
///   - `ntt n ω`:  y[k] = Σⱼ x[j]·ω^(j·k),          ω = 31^((p-1)/n)
///   - `intt n ω`: y[k] = n⁻¹·Σⱼ x[j]·ω^(-j·k)      (1/n baked in)
///   - natural (index) order on both sides, no bit-reversal anywhere.
///
/// Plonky3 (`p3-dft` `TwoAdicSubgroupDft`):
///   - `dft`:  evaluations of the coefficient vector over the subgroup
///     generated by `g = BabyBear::two_adic_generator(log₂ n)`, in natural
///     order (`dft` undoes the internal bit-reversal via
///     `to_row_major_matrix`): y[k] = Σⱼ x[j]·g^(j·k).
///   - `idft`: the inverse, including the 1/n normalization.
///
/// The two agree exactly — same indexing, same normalization — iff `g = ω`.
/// In `p3-baby-bear` 0.5.3 the `TWO_ADIC_GENERATORS` table is the tower
/// 31^((p-1)/2^b), the same generator-31 derivation TRZK uses, so no index
/// permutation and no rescaling is needed. That equality is data, not
/// algebra, so it is asserted here per size: a Plonky3 upgrade that picked a
/// different root would otherwise turn the oracle into a *different
/// transform* that still looks plausible on degenerate inputs.
fn assert_roots_match(n: usize) {
    let log_n = n.trailing_zeros() as usize;
    let g = BabyBear::two_adic_generator(log_n);
    let omega = BabyBear::new(TRZK_GENERATOR).exp_u64(((P - 1) as u64) / n as u64);
    assert_eq!(
        g.as_canonical_u32(),
        omega.as_canonical_u32(),
        "Plonky3 two_adic_generator({log_n}) != TRZK ω = 31^((p-1)/{n}); \
         the transforms are no longer the same — reconcile before trusting the oracle"
    );
}

fn usage() -> ! {
    eprintln!("Usage: p3_oracle --op {{ntt|intt}} --n N [--check]");
    std::process::exit(2);
}

fn parse_args() -> (Op, usize, bool) {
    let mut op = None;
    let mut n = None;
    let mut check = false;
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--op" => match args.next().as_deref() {
                Some("ntt") => op = Some(Op::Ntt),
                Some("intt") => op = Some(Op::Intt),
                other => {
                    eprintln!("--op must be ntt or intt, got {other:?}");
                    std::process::exit(2);
                }
            },
            "--n" => match args.next().and_then(|v| v.parse::<usize>().ok()) {
                Some(v) => n = Some(v),
                None => usage(),
            },
            "--check" => check = true,
            _ => usage(),
        }
    }
    let (Some(op), Some(n)) = (op, n) else { usage() };
    if !n.is_power_of_two() || n < 2 || n.trailing_zeros() as usize > BabyBear::TWO_ADICITY {
        eprintln!(
            "--n must be a power of two in [2, 2^{}], got {n}",
            BabyBear::TWO_ADICITY
        );
        std::process::exit(2);
    }
    (op, n, check)
}

fn parse_values(s: &str, n: usize, what: &str, lineno: usize) -> Result<Vec<u32>, String> {
    let vals: Result<Vec<u32>, _> = s.split_whitespace().map(str::parse).collect();
    let vals = vals.map_err(|e| format!("line {lineno}: non-integer {what}: {e}"))?;
    if vals.len() != n {
        return Err(format!(
            "line {lineno}: expected {n} {what} values, got {}",
            vals.len()
        ));
    }
    if let Some(v) = vals.iter().find(|&&v| v >= P) {
        return Err(format!("line {lineno}: {what} value {v} out of [0, {P})"));
    }
    Ok(vals)
}

fn main() -> ExitCode {
    let (op, n, check) = parse_args();
    assert_roots_match(n);

    let dft = Radix2Dit::<BabyBear>::default();
    let stdin = io::stdin();
    let mut stdout = io::BufWriter::new(io::stdout().lock());

    for (idx, line) in stdin.lock().lines().enumerate() {
        let lineno = idx + 1;
        let line = line.expect("stdin read failed");
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (lhs, rhs) = match line.split_once(':') {
            Some((l, r)) => (l, Some(r)),
            None => (line, None),
        };
        let xs = match parse_values(lhs, n, "input", lineno) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("{e}");
                return ExitCode::from(2);
            }
        };

        let coeffs: Vec<BabyBear> = xs.iter().map(|&v| BabyBear::new(v)).collect();
        let ys: Vec<u32> = match op {
            Op::Ntt => dft.dft(coeffs),
            Op::Intt => dft.idft(coeffs),
        }
        .iter()
        .map(BabyBear::as_canonical_u32)
        .collect();

        if check {
            if let Some(rhs) = rhs {
                let expected = match parse_values(rhs, n, "expected-output", lineno) {
                    Ok(v) => v,
                    Err(e) => {
                        eprintln!("{e}");
                        return ExitCode::from(2);
                    }
                };
                if expected != ys {
                    eprintln!("REFERENCE MISMATCH line {lineno}:");
                    eprintln!("  input    = {xs:?}");
                    eprintln!("  incoming = {expected:?}");
                    eprintln!("  plonky3  = {ys:?}");
                    return ExitCode::FAILURE;
                }
            }
        }

        let xs_str: Vec<String> = xs.iter().map(u32::to_string).collect();
        let ys_str: Vec<String> = ys.iter().map(u32::to_string).collect();
        writeln!(stdout, "{} : {}", xs_str.join(" "), ys_str.join(" "))
            .and_then(|()| stdout.flush())
            .expect("stdout write failed");
    }
    ExitCode::SUCCESS
}
